### ISSUE TITLE
Error while running on Windows

### ISSUE THREAD

**Issue by yashminbhardwaj** [Spyxpo/web-to-app#4]
I am running SWAB(dev) version on my Windows PC, I installed Python3 on my PC and then I opened cloned SWAB folder in my Terminal
 
![Windows PowerShell 11_17_2022 5_39_26 PM](https://user-images.githubusercontent.com/118446108/202442971-d48f44c2-ddf8-4c16-b10b-253c54914a7d.png)

I installed all the modules required using pip, when I ran `run.py` using `python run.py` initially It started downloading Flutter, after that it installed Flutter on my device successfully and after that I am getting this particular error.

I can install NodeJS or other requirements on my own but I want to see if it can auto download and setup the required prerequisites.

**Comment by mantresh-pvt** [comment]
Thank you for reporting this issue, this issue was caused due to an invalid function after downloading NodeJS.

This issue has been resolved for Windows users and has been tested on Windows 11, you can run `update.py` using `python update.py` or `python3 update.py` in the SWAB directory to update your [SWAB dev](https://github.com/Spyxpo/swab/tree/dev) project to the latest dev version, you can also use `git pull` inside the SWAB directory to update your project to the latest version.
